-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 11:43:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AtlanticWarfare
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AtlanticWarfare` ;

-- -----------------------------------------------------
-- Schema AtlanticWarfare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AtlanticWarfare` DEFAULT CHARACTER SET utf8 ;
USE `AtlanticWarfare` ;

-- -----------------------------------------------------
-- Table `AtlanticWarfare`.`Player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AtlanticWarfare`.`Player` ;

CREATE TABLE IF NOT EXISTS `AtlanticWarfare`.`Player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) UNIQUE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `countryCode` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AtlanticWarfare`.`Game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AtlanticWarfare`.`Game` ;

CREATE TABLE IF NOT EXISTS `AtlanticWarfare`.`Game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `winner` INT NULL,
  `loser` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Jogos_Jogador1_idx` (`winner` ASC),
  INDEX `fk_Jogos_Jogador2_idx` (`loser` ASC),
  CONSTRAINT `fk_Jogos_Jogador1`
    FOREIGN KEY (`winner`)
    REFERENCES `AtlanticWarfare`.`Player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogos_Jogador2`
    FOREIGN KEY (`loser`)
    REFERENCES `AtlanticWarfare`.`Player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AtlanticWarfare`.`Statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AtlanticWarfare`.`Statistics` ;

CREATE TABLE IF NOT EXISTS `AtlanticWarfare`.`Statistics` (
  `player_id` INT NOT NULL,
  `gamesPlayed` INT NOT NULL DEFAULT 0 CHECK(gamesPlayed>=0),
  `gamesWon` INT NOT NULL DEFAULT 0 CHECK(gamesWon>=0),
  `gamesLost` INT NOT NULL DEFAULT 0 CHECK(gamesLost>=0),
  PRIMARY KEY (`player_id`),
  INDEX `fkStatistics_Jogador_idx` (`player_id` ASC),
  CONSTRAINT `fk_Statistics_Jogador`
    FOREIGN KEY (`player_id`)
    REFERENCES `AtlanticWarfare`.`Player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
