-- MySQL Script generated by MySQL Workbench
-- Fri Nov 27 14:40:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AtlanticWarfare
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AtlanticWarfare` ;

-- -----------------------------------------------------
-- Schema AtlanticWarfare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AtlanticWarfare` DEFAULT CHARACTER SET utf8 ;
USE `AtlanticWarfare`;

-- -----------------------------------------------------
-- Table `AtlanticWarfare`.`Jogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AtlanticWarfare`.`Jogador` ;

CREATE TABLE IF NOT EXISTS `AtlanticWarfare`.`Jogador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL UNIQUE,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AtlanticWarfare`.`Jogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AtlanticWarfare`.`Jogo` ;

CREATE TABLE IF NOT EXISTS `AtlanticWarfare`.`Jogo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Jogador1_id` INT NOT NULL,
  `Jogador2_id` INT NOT NULL,
  `vencedor` INT NOT NULL,
  PRIMARY KEY (`id`, `Jogador1_id`, `Jogador2_id`),
  INDEX `fk_Jogos_Jogador1_idx` (`Jogador1_id` ASC),
  INDEX `fk_Jogos_Jogador2_idx` (`Jogador2_id` ASC),
  CONSTRAINT `fk_Jogos_Jogador1`
    FOREIGN KEY (`Jogador1_id`)
    REFERENCES `AtlanticWarfare`.`Jogador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogos_Jogador2`
    FOREIGN KEY (`Jogador2_id`)
    REFERENCES `AtlanticWarfare`.`Jogador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AtlanticWarfare`.`Estatistica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AtlanticWarfare`.`Estatistica` ;

CREATE TABLE IF NOT EXISTS `AtlanticWarfare`.`Estatistica` (
  `Jogador_id` INT NOT NULL,
  `jogosJogados` INT NOT NULL DEFAULT 0 CHECK (jogosJogados=jogosGanhos+jogosPerdidos),
  `jogosGanhos` INT NOT NULL DEFAULT 0,
  `jogosPerdidos` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Jogador_id`),
  INDEX `fk_Estatistica_Jogador_idx` (`Jogador_id` ASC),
  CONSTRAINT `fk_Estatistica_Jogador`
    FOREIGN KEY (`Jogador_id`)
    REFERENCES `AtlanticWarfare`.`Jogador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
